### ISSUE TITLE
小数点を含む話数を正しく扱えない

### ISSUE THREAD

**Issue by YDKK** [kirimin/Annictroid#1]
91Days (https://annict.com/works/4793) の最新話のような、小数点を含む話数を正しく扱えていないようです。
常に「通信に失敗したようです。」と表示されます。

**Comment by kirimin** [comment]
報告ありがとうございます！
すみません、対応します！

**Comment by kirimin** [comment]
バージョン0.4.2で修正しました。

**Comment by YDKK** [comment]
確認しました。
素早い対応ありがとうございます！
