### ISSUE TITLE
annict-userland

### ISSUE THREAD

**Issue by koshien2015** [kirimin/Annictroid#2]
annictroid使わせていただいております。
本来Issueに書くべきではないのですが、他に方法が思いつきませんで…。
annict内にAPIを使ったアプリ一覧のページができました。
http://blog.annict.com/post/159359910633/annict-userland
他薦は受け付けていないということで開発者ご本人が登録していただければと思います。
失礼いたしました。

**Comment by kirimin** [comment]
教えて頂きありがとうございます！！！
登録します！！！

**Comment by kirimin** [comment]
登録しましたー
